[tox]
skipsdist = True
envlist =
    lint
    mypy
    pylint

[testenv]
# Top level section - as a base for other environments. Should not be used directly
skip_install = true
runner = uv-venv-lock-runner

[testenv:lint]
commands =
    uv run ruff check .
    uv run ruff format --check

[testenv:mypy]
commands = uv run mypy .

[testenv:pylint]
commands = uv run pylint --rcfile .pylintrc --verbose --output-format=colorized --fail-under=10.0 src/
